version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bbs_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./bbsAppDb/db/data:/var/lib/mysql
      - ./bbsAppDb/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./bbsAppDb/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3300:3300

  app:
    image: node:16
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./bbsApp:/app
    working_dir: /app
    command: >
      bash -c 'npm install &&
      npm start'
